# Generated by Django 5.1.4 on 2025-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('BYR', models.FloatField(blank=True, null=True)),
                ('USD', models.FloatField(blank=True, null=True)),
                ('EUR', models.FloatField(blank=True, null=True)),
                ('KZT', models.FloatField(blank=True, null=True)),
                ('UAH', models.FloatField(blank=True, null=True)),
                ('AZN', models.FloatField(blank=True, null=True)),
                ('KGS', models.FloatField(blank=True, null=True)),
                ('UZS', models.FloatField(blank=True, null=True)),
                ('GEL', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_currencyrate',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
